# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: wdi5 browser-scope tests

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install packages
        run: yarn install --frozen-lockfile
      - name: run basic.test.js w/ ui5 tooling
        run: HEADLESS=true yarn test:ci:wdi5:withUI5tooling
      - name: run wdi5 tests w/ regular webserver
        run: HEADLESS=true yarn test:ci:wdi5
      - name: run wdi5 tests w/ regular webserver against multiple ui5 versions
        run: HEADLESS=true yarn test:ci:multiversion
